name: GitHub Actions Demo
on: pull_request
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/checkov-action@master
        env:
            PRISMA_API_URL: https://api0.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
