name: GitHub Actions Demo
on: pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        env:
            PRISMA_API_URL: https://api0.prismacloud.io
        with:
            api-key: ${{ secrets.BC_API_KEY }}
