name: build
on:
  pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master 
        env:
          BC_API_URL: https://a99eg4dega.execute-api.us-west-2.amazonaws.com/v1
        with:
          api-key: ${{ secrets.BC_API_KEY }}
